// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(DashContext))]
    [Migration("20181005174857_SeedCatalogInstrument")]
    partial class SeedCatalogInstrument
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("DataLayer.Entities.CatInstrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CatInstruments");

                    b.HasData(
                        new { Id = 1, Name = "Savings" },
                        new { Id = 2, Name = "Equity MX" },
                        new { Id = 3, Name = "Debt MX" },
                        new { Id = 4, Name = "Others MX" },
                        new { Id = 5, Name = "Equity Tech USA" },
                        new { Id = 6, Name = "Equity USA" },
                        new { Id = 7, Name = "Debt USA" }
                    );
                });

            modelBuilder.Entity("DataLayer.Entities.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<float>("Taxes");

                    b.HasKey("Id");

                    b.ToTable("Configuration");
                });

            modelBuilder.Entity("DataLayer.Entities.ConfigurationInstrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CatInstrumentsId");

                    b.Property<int?>("ConfigurationId");

                    b.Property<float>("Percentaje");

                    b.HasKey("Id");

                    b.HasIndex("CatInstrumentsId");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("ConfigurationInstruments");
                });

            modelBuilder.Entity("DataLayer.Entities.HistoricalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ConfigurationId");

                    b.Property<DateTime>("Date");

                    b.Property<float>("Gain");

                    b.Property<int?>("SectionId");

                    b.Property<float>("Total");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("SectionId");

                    b.ToTable("HistoricalEntries");
                });

            modelBuilder.Entity("DataLayer.Entities.Plugin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Plugins");
                });

            modelBuilder.Entity("DataLayer.Entities.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ConfigurationRefId");

                    b.Property<string>("Description");

                    b.Property<float>("Gain");

                    b.Property<string>("Name");

                    b.Property<int?>("PluginId");

                    b.Property<float>("Total");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationRefId")
                        .IsUnique();

                    b.HasIndex("PluginId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("DataLayer.Entities.ConfigurationInstrument", b =>
                {
                    b.HasOne("DataLayer.Entities.CatInstrument", "CatInstruments")
                        .WithMany("ConfigurationInstrument")
                        .HasForeignKey("CatInstrumentsId");

                    b.HasOne("DataLayer.Entities.Configuration", "Configuration")
                        .WithMany("ConfigurationInstruments")
                        .HasForeignKey("ConfigurationId");
                });

            modelBuilder.Entity("DataLayer.Entities.HistoricalEntry", b =>
                {
                    b.HasOne("DataLayer.Entities.Configuration", "Configuration")
                        .WithMany("HistoricalEntries")
                        .HasForeignKey("ConfigurationId");

                    b.HasOne("DataLayer.Entities.Section", "Section")
                        .WithMany("Sections")
                        .HasForeignKey("SectionId");
                });

            modelBuilder.Entity("DataLayer.Entities.Section", b =>
                {
                    b.HasOne("DataLayer.Entities.Configuration", "Configuration")
                        .WithOne("Section")
                        .HasForeignKey("DataLayer.Entities.Section", "ConfigurationRefId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataLayer.Entities.Plugin", "Plugin")
                        .WithMany("Sections")
                        .HasForeignKey("PluginId");
                });
#pragma warning restore 612, 618
        }
    }
}
