// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(DashContext))]
    partial class DashContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("DataLayer.Entities.CatInstrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CatInstrumments");
                });

            modelBuilder.Entity("DataLayer.Entities.Configuration", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name");

                    b.Property<float>("Taxes");

                    b.HasKey("Id");

                    b.ToTable("Configuration");
                });

            modelBuilder.Entity("DataLayer.Entities.ConfigurationInstrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CatInstrumentsId");

                    b.Property<int?>("ConfigurationId");

                    b.Property<float>("Percentaje");

                    b.HasKey("Id");

                    b.HasIndex("CatInstrumentsId");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("ConfigurationInstruments");
                });

            modelBuilder.Entity("DataLayer.Entities.HistoricalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ConfigurationId");

                    b.Property<DateTime>("Date");

                    b.Property<float>("Gain");

                    b.Property<int?>("SectionId");

                    b.Property<float>("Total");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("SectionId");

                    b.ToTable("HistoricalEntries");
                });

            modelBuilder.Entity("DataLayer.Entities.Plugin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Plugins");
                });

            modelBuilder.Entity("DataLayer.Entities.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<float>("Gain");

                    b.Property<string>("Name");

                    b.Property<int?>("PluginId");

                    b.Property<float>("Total");

                    b.HasKey("Id");

                    b.HasIndex("PluginId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("DataLayer.Entities.Configuration", b =>
                {
                    b.HasOne("DataLayer.Entities.Section", "Section")
                        .WithOne("Configuration")
                        .HasForeignKey("DataLayer.Entities.Configuration", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataLayer.Entities.ConfigurationInstrument", b =>
                {
                    b.HasOne("DataLayer.Entities.CatInstrument", "CatInstruments")
                        .WithMany("ConfigurationInstrument")
                        .HasForeignKey("CatInstrumentsId");

                    b.HasOne("DataLayer.Entities.Configuration", "Configuration")
                        .WithMany("ConfigurationInstruments")
                        .HasForeignKey("ConfigurationId");
                });

            modelBuilder.Entity("DataLayer.Entities.HistoricalEntry", b =>
                {
                    b.HasOne("DataLayer.Entities.Configuration", "Configuration")
                        .WithMany("HistoricalEntries")
                        .HasForeignKey("ConfigurationId");

                    b.HasOne("DataLayer.Entities.Section", "Section")
                        .WithMany("Sections")
                        .HasForeignKey("SectionId");
                });

            modelBuilder.Entity("DataLayer.Entities.Section", b =>
                {
                    b.HasOne("DataLayer.Entities.Plugin", "Plugin")
                        .WithMany("Sections")
                        .HasForeignKey("PluginId");
                });
#pragma warning restore 612, 618
        }
    }
}
